# -*- coding: utf-8 -*-
"""BriososCoach

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pX_MqkBVPX85D5RCv8awg-ujUjVaPek2
"""

# Guarda este código con los nombres CORRECTOS en 'app.py'

import os
import streamlit as st
from typing import Annotated, Sequence, TypedDict
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage
from langchain_core.tools import tool

# EL NOMBRE REAL: ChatGoogleGenerativeAI y GoogleGenerativeAIEmbeddings
from langchain_google_genai import ChatGoogleGenerativeAI, GoogleGenerativeAIEmbeddings

from langchain_core.vectorstores import InMemoryVectorStore
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode

# 1. CONFIGURACIÓN VISUAL
st.set_page_config(page_title="BRIOSOS Coach AI", layout="centered")
st.title("⚡ BRIOSOS: Coach de Estructura y Rendimiento")
st.caption("Optimización Masculina Autónoma | Conectado a la filosofía y herramientas de Briosos.org")

# 2. VALIDACIÓN DE CREDENCIALES
google_key = os.environ.get("GEMINI_API_KEY") or st.sidebar.text_input("Ingresa tu Gemini API Key", type="password")

if not google_key:
    st.info("Por favor, ingresa tu API Key de Gemini en la barra lateral para activar al Coach.")
    st.stop()

# 3. BASE DE DATOS VECTORIAL
@st.cache_resource
def inicializar_base_datos_briosos():
    documentos_briosos = [
        "Filosofía Briosos: Un hombre solo podrá ser libre cuando alcance el dominio de sí mismo. El fin es impulsar el éxito construyendo un carácter resuelto y enérgico, aportando estructura y simplicidad.",
        "Herramienta - Constructor de Hábitos: Cambiará tu vida. Registra y verifica qué tan consistente eres. Filosofía: 'Lo que no se mide no se puede mejorar'. Úsalo para trackear disciplinas innegociables diariamente.",
        "Herramienta - Planeador Diario: El tiempo es el activo más escaso. Estructura tu día 15 minutos antes de ir a dormir. Al hacer esto el día anterior, eliminas la fatiga de decisión y te levantas con un mapa de acción claro.",
        "Herramienta - Planeador Semanal: Todos los días no son iguales. Agrupa tareas por temática en distintos días de la semana (ej: Lunes de finanzas, Martes de contenido) para mantener foco profundo y evitar el desgaste.",
        "Producto - Creatina Old School: Fuerza y recuperación pura. Rinde por 2 meses, 5gr por porción. Precio: $110.000 COP. Envío gratis a Medellín y alrededores. Compra directa haciendo clic en el botón de WhatsApp de la web.",
        "Producto - Creatina en Gomitas: Rendimiento y practicidad. Rinde 30 días, la porción de 5gr son 4 gomitas. Precio: $140.000 COP. Envío gratis a Medellín y alrededores. Compra directa por WhatsApp.",
        "Producto - Aminoácidos Esenciales: Optimiza la síntesis de proteína y frena el catabolismo. Rinde 30 días, 15gr por día. Precio: $100.000 COP. Envío gratis a Medellín. Compra por WhatsApp.",
        "Comunidad - La Tribu de BRIOSOS: Red de contactos para hombres que valoran tu tiempo y esfuerzo. Acceso al grupo mediante el botón de la Tribu en la web."
    ]

    text_splitter = RecursiveCharacterTextSplitter(chunk_size=300, chunk_overlap=30)
    docs = text_splitter.create_documents(documentos_briosos)

    # Aquí también se corrigió el nombre de la clase
    embeddings = GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-2", google_api_key=google_key)
    vector_store = InMemoryVectorStore.from_documents(docs, embeddings)
    return vector_store.as_retriever(search_kwargs={"k": 2})

retriever = inicializar_base_datos_briosos()

# 4. CAPACIDAD DE BÚSQUEDA DEL AGENTE
@tool
def buscar_en_base_de_datos(query: str) -> str:
    """Busca información en la base de datos de Briosos sobre herramientas (hábitos, planeadores), suplementos o filosofía."""
    docs = retriever.invoke(query)
    return "\n\n".join([doc.page_content for doc in docs])

tools = [buscar_en_base_de_datos]
tool_node = ToolNode(tools)

# 5. ARQUITECTURA DE CONTROL (LangGraph)
class AgentState(TypedDict):
    messages: Annotated[Sequence[BaseMessage], add_messages]

# Aquí también se corrigió el nombre de la clase
llm = ChatGoogleGenerativeAI(model="gemini-3.5-flash", temperature=0.3, google_api_key=google_key).bind_tools(tools)

def call_model(state: AgentState):
    response = llm.invoke(state["messages"])
    return {"messages": [response]}

def router_logic(state: AgentState):
    last_message = state["messages"][-1]
    if last_message.tool_calls:
        return "execute_tools"
    return END

workflow = StateGraph(AgentState)
workflow.add_node("agent", call_model)
workflow.add_node("tools", tool_node)

workflow.add_edge(START, "agent")
workflow.add_conditional_edges("agent", router_logic, {"execute_tools": "tools", END: END})
workflow.add_edge("tools", "agent")

agentic_graph = workflow.compile()

# 6. ENTORNO DE CONVERSACIÓN
if "chat_history" not in st.session_state:
    st.session_state.chat_history = [AIMessage(content="Bienvenido a la Tribu. Soy tu Coach de IA. ¿Qué área de tu vida vamos a estructurar u optimizar hoy?")]

for message in st.session_state.chat_history:
    with st.chat_message("user" if isinstance(message, HumanMessage) else "assistant"):
        st.write(message.content)

if user_input := st.chat_input("Ej: ¿Cómo organizo mi día con el planeador o qué creatina compro?"):
    st.session_state.chat_history.append(HumanMessage(content=user_input))
    with st.chat_message("user"):
        st.write(user_input)

    with st.chat_message("assistant"):
        with st.spinner("Pensando como un hombre de propósito..."):
            inputs = {"messages": st.session_state.chat_history}
            output = agentic_graph.invoke(inputs)
            final_response = output["messages"][-1].content
            st.write(final_response)
            st.session_state.chat_history.append(AIMessage(content=final_response))
